# Generated by Django 4.2.2 on 2024-05-18 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.conjunto')),
            ],
        ),
        migrations.CreateModel(
            name='ParqueaderoVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('apartamento', models.CharField(max_length=50)),
                ('tipo_doc', models.CharField(max_length=20)),
                ('doc', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('hora_ingreso', models.DateTimeField()),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('parqueadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.parqueadero')),
            ],
        ),
        migrations.CreateModel(
            name='ParqueaderoPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('apartamento', models.CharField(max_length=50)),
                ('propietario', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('parqueadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.parqueadero')),
            ],
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novedad', models.CharField(max_length=200)),
                ('parqueadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.parqueadero')),
            ],
        ),
    ]
