# Generated by Django 4.2.2 on 2024-05-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parqueaderopropietario',
            old_name='propietario',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='parqueaderovisitante',
            old_name='doc',
            new_name='documento',
        ),
        migrations.AddField(
            model_name='parqueadero',
            name='tipoVehiculo',
            field=models.CharField(choices=[('Moto', 'Parqueadero para motos'), ('Carro', 'Parqueadero para carros'), ('Bicicleta', 'Parqueadero para bicicletas')], default=1, max_length=100, verbose_name='tipo de vehiculo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='tipo',
            field=models.CharField(choices=[('Privado', 'Parqueadero privado - propietarios'), ('Publico', 'Parqueadero publico - visitantes')], max_length=100, verbose_name='tipo de parqueadero'),
        ),
        migrations.AlterField(
            model_name='parqueaderopropietario',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
